services:

  frontend:
    build: 
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - tasksync_net

  backend:
    build: 
      context: ./backend
    env_file:
      - .env
    environment:
      - DATABASE_URL
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    command: >
      sh -c "php bin/console doctrine:migrations:migrate --no-interaction && 
             php -S 0.0.0.0:8000 -t public"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - tasksync_net

  database:
    hostname: ${POSTGRES_HOST}
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - tasksync_net

networks:
  tasksync_net:
    driver: bridge

volumes:
  database_data:
