services:
  symfony:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
